name: lint
run-name: Executing ESLint
on: [pull_request, workflow_dispatch]
jobs:
    lint:
        name: Executing ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: NPM install
              run: |
                  npm ci

            - name: Lint
              run: npm run lint
